Repository gg-mike/IO-I42-Gamma-Text, pull requests merged in 2021-12, with the labels that each got.

#6 Rest api
  .gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  ioprojectarchitecture.iml
  pom.xml
  src/main/java/pl/put/poznan/transformer/TextTransformerApplication.java
  src/main/java/pl/put/poznan/transformer/config/RequestLoggingFilterConfig.java
  src/main/java/pl/put/poznan/transformer/controllers/TextTransformerController.java
  src/main/java/pl/put/poznan/transformer/exceptions/TextTransformNotFoundException.java
  src/main/java/pl/put/poznan/transformer/logic/TextTransformer.java
  src/main/java/pl/put/poznan/transformer/models/RequestTextTransformModel.java
  src/main/java/pl/put/poznan/transformer/models/ResponseTextTransformModel.java
  src/main/java/pl/put/poznan/transformer/rest/TextTransformerController.java
  src/main/java/pl/put/poznan/transformer/services/TextTransformerService.java
  src/main/java/pl/put/poznan/transformer/texttransformers/ExampleTextTransformer.java
  src/main/java/pl/put/poznan/transformer/texttransformers/TextTransformer.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  target/classes/application.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: high

#7 GitHub Actions
  .github/workflows/ci.yml
  README.md
  pom.xml
  src/main/java/pl/put/poznan/transformer/config/RequestLoggingFilterConfig.java
  src/main/java/pl/put/poznan/transformer/controllers/TextTransformerController.java
  src/main/java/pl/put/poznan/transformer/exceptions/TextTransformNotFoundException.java
  src/main/java/pl/put/poznan/transformer/models/RequestTextTransformModel.java
  src/main/java/pl/put/poznan/transformer/models/ResponseTextTransformModel.java
  src/main/java/pl/put/poznan/transformer/services/TextTransformerService.java
  src/main/java/pl/put/poznan/transformer/texttransformers/ExampleTextTransformer.java
  src/main/java/pl/put/poznan/transformer/texttransformers/TextTransformer.java
  src/main/resources/application.yml
Labels: low

#8 Reverse Text Transformer
  src/main/java/pl/put/poznan/transformer/texttransformers/ReverseTextTransformer.java
  src/test/java/pl/put/poznan/transformer/texttransformers/ReverseTextTransformerTest.java
Labels: medium

#9 Latex Text Transformer
  src/main/java/pl/put/poznan/transformer/texttransformers/LatexTextTransformer.java
  src/test/java/pl/put/poznan/transformer/texttransformers/LatexTextTransformerTest.java
Labels: low

#15 add javadoc.yml
  .github/workflows/javadoc.yml
Labels: medium

#19 Logowanie
  docs/allclasses-index.html
  docs/allpackages-index.html
  docs/help-doc.html
  docs/index-all.html
  docs/index.html
  docs/overview-summary.html
  docs/overview-tree.html
  docs/pl/put/poznan/transformer/TextTransformerApplication.html
  docs/pl/put/poznan/transformer/class-use/TextTransformerApplication.html
  docs/pl/put/poznan/transformer/config/RequestLoggingFilterConfig.html
  docs/pl/put/poznan/transformer/config/class-use/RequestLoggingFilterConfig.html
  docs/pl/put/poznan/transformer/config/package-summary.html
  docs/pl/put/poznan/transformer/config/package-tree.html
  docs/pl/put/poznan/transformer/config/package-use.html
  docs/pl/put/poznan/transformer/controllers/TextTransformerController.html
  docs/pl/put/poznan/transformer/controllers/class-use/TextTransformerController.html
  docs/pl/put/poznan/transformer/controllers/package-summary.html
  docs/pl/put/poznan/transformer/controllers/package-tree.html
  docs/pl/put/poznan/transformer/controllers/package-use.html
  docs/pl/put/poznan/transformer/exceptions/TextTransformNotFoundException.html
  docs/pl/put/poznan/transformer/exceptions/class-use/TextTransformNotFoundException.html
  docs/pl/put/poznan/transformer/exceptions/package-summary.html
  docs/pl/put/poznan/transformer/exceptions/package-tree.html
  docs/pl/put/poznan/transformer/exceptions/package-use.html
  docs/pl/put/poznan/transformer/models/RequestTextTransformModel.html
  docs/pl/put/poznan/transformer/models/ResponseTextTransformModel.html
  docs/pl/put/poznan/transformer/models/class-use/RequestTextTransformModel.html
  docs/pl/put/poznan/transformer/models/class-use/ResponseTextTransformModel.html
  docs/pl/put/poznan/transformer/models/package-summary.html
  docs/pl/put/poznan/transformer/models/package-tree.html
  docs/pl/put/poznan/transformer/models/package-use.html
  docs/pl/put/poznan/transformer/package-summary.html
  docs/pl/put/poznan/transformer/package-tree.html
  docs/pl/put/poznan/transformer/package-use.html
  docs/pl/put/poznan/transformer/services/TextTransformerService.html
  docs/pl/put/poznan/transformer/services/class-use/TextTransformerService.html
  docs/pl/put/poznan/transformer/services/package-summary.html
  docs/pl/put/poznan/transformer/services/package-tree.html
  docs/pl/put/poznan/transformer/services/package-use.html
  docs/pl/put/poznan/transformer/texttransformers/ExampleTextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/LatexTextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/ReverseTextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/TextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/class-use/ExampleTextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/class-use/LatexTextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/class-use/ReverseTextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/class-use/TextTransformer.html
  docs/pl/put/poznan/transformer/texttransformers/package-summary.html
  docs/pl/put/poznan/transformer/texttransformers/package-tree.html
  docs/pl/put/poznan/transformer/texttransformers/package-use.html
  docs/serialized-form.html
  src/main/java/pl/put/poznan/transformer/texttransformers/LatexTextTransformer.java
  src/main/java/pl/put/poznan/transformer/texttransformers/ReverseTextTransformer.java
Labels: medium
